<div id="infobox" class="mini">
	<!-- <h2>What is this?</h2>
	<p>toss140.net is a crowdsourced summary of newspaper columnists, so you can be on top of the pundits, and decide if you want to read them.</p> -->

	<h2>How do I write a summary?</h2>
	<p>Just twitter your summary, and include a link to the piece you're summarising (shortened is fine, we are very clever). As long as you include the hashtag <code>#toss140</code>, we will find your tweet and the web site will do the rest, deducing the author name, the newspaper title, the date, etc.</p>

	<h2>How can I keep up with new posts?</h2>
	<p>You can <a href="http://twitter.com/toss140">follow us on Twitter</a>. All new summaries are automatically posted to the Twitter account <a href="http://twitter.com/toss140">toss140</a>.</p>
	
	<h2>Any other questions?</h2>
	<p>See the <a href="/about{{q}}">information page</a>.
</div>