<div id="infobox" class="mini">
	<h2>what is this?</h2>
	<p>toss140.net is a crowdsourced summary of newspaper columnists, so you can be on top of the pundits, and decide if you want to read them.</p>

	<h2>how do i write a summary?</h2>
	<p>just twitter your summary, and include a link to the piece you're summarising (shortened is fine, we are very clever). as long as you include the hashtag <code>#toss140</code>, we will find your tweet and the website will do the rest, deducing the author name, the newspaper title, the date, etc.</p>
</div>