<h2>what is this?</h2>
<p>toss140.net is a crowdsourced summary of newspaper columnists, so you can be on top of the pundits, and decide if you want to read them.</p>

<h2>how do i write a summary?</h2>
<p>just twitter your summary, and include a link to the piece you're summarising (shortened is fine, we are very clever). as long as you include the hashtag <code>#toss140</code>, we will find your tweet and the website will do the rest, deducing the author name, the newspaper title, the date, etc.</p>

<h2>cool, but the page is messy?</h2>
<p>it was built on a whim yesterday in response to <a href="http://twitter.com/bengoldacre/status/2514941842">this tweet</a>. if you tweet a summary right now, we will polish it tomorrow, so that the page is organised by author, date, and newspaper. then we will make it pretty, then we will pimp it to the world.</p>

<h2>truly you are people of action!</h2>
<p>we are.</p>
