application: toss140
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: toss.py

- url: /about
  script: toss.py

- url: /timeline(/\d{4}-\d\d-\d\d)?
  script: toss.py

- url: /recent(/\d{4}-\d\d-\d\d)?
  script: toss.py

- url: /author/[^/]+
  script: toss.py

- url: /tweeter/[^/]+
  script: toss.py

- url: /organ/[^/]+
  script: toss.py

- url: /date/\d{4}-\d\d-\d\d
  script: toss.py

- url: /linkless
  script: toss.py

- url: /do/update
  script: update.py

- url: /do/add-tweet
  script: update.py
  login: admin # Invoked only by task queue

- url: /do/index-tweets
  script: update.py
  login: admin # Not really used at all any more. Could be useful on rare occasions

- url: /do/index-tweet
  script: update.py
  login: admin # Invoked by task queue and 'r' link from god mode

- url: /do/retweet
  script: update.py

- url: /(toss\.css)
  static_files: \1
  upload: toss\.css

- url: /(.*\.png)
  static_files: \1
  upload: .*\.png

- url: /(js/.*\.js)
  static_files: \1
  upload: js/.*\.js

- url: /login
  login: admin
  script: toss.py

- url: /admin(/.*)?
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin # DO NOT REMOVE

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin # DO NOT REMOVE
